services:
    accounts:
      image: sujayskill/accounts:latest
      ports:
        - "8081:8081"
      networks:
        - bank-network
    cards:
      image: sujayskill/cards:latest
      ports: 
        - "8082:8082"
      networks: 
        - bank-network
    loans:
      image: sujayskill/cards:latest
      ports: 
        - "8082:8082"
      networks: 
        - bank-network
    insurance:
      image: sujayskill/cards:latest
      ports: 
        - "8082:8082"
      networks: 
        - bank-network
networks:
  bank-network: {}     